name: flutist
description: "A Flutter project management framework inspired by Tuist"
version: 1.0.5
homepage: https://github.com/seonwooke/flutist
repository: https://github.com/seonwooke/flutist
issue_tracker: https://github.com/seonwooke/flutist/issues
documentation: https://github.com/seonwooke/flutist#readme

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  io: ^1.0.5
  yaml_edit: ^2.2.3
  yaml: ^3.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  flutist:
